"""
augment.py — Paraphrase augmentation pipeline for KAN-Route.

Problem: Training data generated by a single LLM is phrased in that model's
style. The router learns "LLM-speak → tools" rather than "human-speak → tools".

Fix: For each query, generate 3 paraphrases with varied vocabulary and syntax
using the same model with higher temperature. This expands the corpus ~4x
and substantially reduces sensitivity to surface-level phrasing patterns.

Result: Qwen corpus 9,903 → 39,400 samples with paraphrase augmentation.
"""

import json
import time
from pathlib import Path
from tqdm.auto import tqdm


PARAPHRASE_SYSTEM = (
    "You are a query paraphraser. "
    "Given a user query, rewrite it in 3 different ways. "
    "Use different vocabulary, sentence structure, and phrasing each time. "
    "Preserve the exact intent. Output ONLY valid JSON, no markdown."
)


def build_paraphrase_prompt(query: str, tokenizer) -> str:
    """Build a chat-formatted paraphrase prompt."""
    messages = [
        {"role": "system", "content": PARAPHRASE_SYSTEM},
        {
            "role": "user",
            "content": (
                f'Paraphrase this query 3 ways:\n"{query}"\n\n'
                'Output ONLY this JSON:\n'
                '[{"paraphrase": "..."}, {"paraphrase": "..."}, {"paraphrase": "..."}]'
            ),
        },
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def parse_paraphrases(raw: str) -> list:
    """Parse paraphrase JSON output with markdown fence stripping."""
    try:
        raw = raw.strip()
        if "```" in raw:
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw)
        return [d["paraphrase"] for d in data if "paraphrase" in d]
    except Exception:
        return []


def augment_with_paraphrases(
    raw_dataset: list,
    teacher,
    tokenizer,
    device: str = "cuda",
    batch_size: int = 16,
    max_samples: int = None,
    cache_path: str = None,
) -> list:
    """
    Generate paraphrases for every query in raw_dataset and return an
    expanded dataset combining originals + paraphrases.

    Args:
        raw_dataset  : Original list of {query, tool, tool_id, img_id, objects}
        teacher      : Loaded LLM (same model used for query generation)
        tokenizer    : Corresponding tokenizer
        device       : CUDA or CPU
        batch_size   : Paraphrase batch size (16 recommended for T4)
        max_samples  : Limit augmentation to first N samples (None = all)
        cache_path   : If provided, save/load augmented dataset

    Returns:
        Combined list of original + paraphrase records.
        Each paraphrase record has 'source': 'paraphrase'; originals have 'source': 'original'.
    """
    import torch

    if cache_path and Path(cache_path).exists():
        print(f"Loading cached augmented dataset from {cache_path}")
        with open(cache_path) as f:
            return json.load(f)

    source = raw_dataset[:max_samples] if max_samples else raw_dataset
    queries = [r["query"] for r in source]

    tokenizer.padding_side = "left"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    augmented = []
    failed    = 0
    t0 = time.time()

    for start in tqdm(range(0, len(queries), batch_size), desc="Paraphrasing"):
        batch_queries = queries[start : start + batch_size]
        batch_records = source[start : start + batch_size]
        batch_prompts = [build_paraphrase_prompt(q, tokenizer) for q in batch_queries]

        inputs = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=512,
        ).to(device)

        with torch.no_grad():
            output_ids = teacher.generate(
                **inputs,
                max_new_tokens=200,
                do_sample=True,
                temperature=0.8,   # Higher temp = more lexical diversity
                top_p=0.95,
                pad_token_id=tokenizer.pad_token_id,
            )

        input_len = inputs["input_ids"].shape[1]

        for out, record in zip(output_ids, batch_records):
            raw_text    = tokenizer.decode(out[input_len:], skip_special_tokens=True)
            paraphrases = parse_paraphrases(raw_text)

            if not paraphrases:
                failed += 1
                continue

            for p in paraphrases:
                if len(p.strip()) > 5:
                    augmented.append({
                        "img_id" : record["img_id"],
                        "query"  : p.strip(),
                        "tool"   : record["tool"],
                        "tool_id": record["tool_id"],
                        "objects": record["objects"],
                        "source" : "paraphrase",
                    })

    elapsed = time.time() - t0
    print(f"\n✅ Generated {len(augmented)} paraphrases in {elapsed / 60:.1f} min | {failed} failed")

    # Tag originals and combine
    tagged_originals = [{**r, "source": "original"} for r in source]
    combined = tagged_originals + augmented

    if cache_path:
        with open(cache_path, "w") as f:
            json.dump(combined, f)
        print(f"Saved augmented dataset ({len(combined)} samples) to {cache_path}")

    print(f"\nDataset: {len(source):,} → {len(combined):,} samples ({len(combined)/len(source):.1f}x growth)")
    return combined
